"""Dados dos membros – Apostolado da Oração · Paróquia São Jorge · Nova Odessa."""
import datetime

# (id, num_orig, nome, sexo, nasc, ingresso, endereco, bairro, telefone,
#  funcao, situacao, consagrada, observacoes, pagina)
MEMBROS = [
    (1, "1", "Alice Euzébio Pereira", "F", datetime.date(1958, 11, 25), None,
     "Rua João Batista de Almeida, 47", "Nova Odessa", "(19) 99131-5952", "",
     "Inativo", "Não", "Não é membro ativo na comunidade.", "p.6"),
    (2, "2", "Ana Borges", "F", datetime.date(1942, 9, 29), None,
     "", "", "", "", "Ativo", "Não", "Registro mínimo – somente nome e aniversário.", "p.6"),
    (3, "3", "Aparecida Petri", "F", datetime.date(1956, 1, 20), None,
     "Rua Sebastião Cardoso, s/n", "Nova Odessa", "(19) 99389-6167", "",
     "Ativo", "Não", "", "p.6"),
    (4, "4", "Argemira dos Santos (Mirinha)", "F", datetime.date(1951, 7, 28),
     datetime.date(2017, 7, 7), "Rua da Paz, 261", "Terranova", "(19) 99186-4603", "",
     "Ativo", "Não", "Pertence ao Apostolado desde 07/07/2017 – Paróquia Sta. Luzia – Pe. Luiz Antônio.", "p.6"),
    (5, "5", "Antônio", "M", datetime.date(1944, 11, 22), None,
     "", "", "", "", "Ativo", "Não", "Sobrenome não registrado no livro.", "p.6"),
    (6, "6", "Cacilda Batista Pegan", "F", datetime.date(1939, 8, 12),
     datetime.date(2014, 1, 1), "Alameda do Saber, 23", "Jd. Fibra", "(19) 99755-????", "",
     "Ativo", "Não", "Comunidade de Santa Luzia desde 2014.", "p.6"),
    (8, "8", "Célia Aparecida", "F", datetime.date(1971, 6, 29), None,
     "", "", "", "", "Ativo", "Não", "Nº 7 ausente entre Cacilda e Célia.", "p.6"),
    (9, "9", "Cristina Ellem Santos", "F", datetime.date(1980, 7, 9),
     datetime.date(2017, 7, 7), "Rua Jordano Milani, 142", "N. Sra. de Fátima",
     "(19) 98117-4110", "", "Ativo", "Não",
     "Pertence ao Apostolado desde 07/07/2017 – Paróquia Sta. Luzia – Pe. Luís Antônio.", "p.6b"),
    (10, "10", "Lucas Caixeta Silva", "M", datetime.date(1984, 8, 31),
     datetime.date(2017, 7, 7), "Rua Jordano Milani, 142", "N. Sra. de Fátima",
     "(19) 98129-1150", "", "Ativo", "Não",
     "Pertence ao Apostolado desde 07/07/2017 – Paróquia de Santa Luzia – Pe. Luís Antônio.", "p.6b"),
    (11, "11", "Claudionice Batista Fernandes (Jau)", "F", datetime.date(1972, 7, 8), None,
     "Rua Maximiliano Dal Medico, 290", "Santa Luíza II", "(19) 99528-3882", "Catequista",
     "Ativo", "Não", "Apelido: Jau. Catequista – Comunidade Santa Luzia.", "p.6b"),
    (12, "12", "Cleide", "F", datetime.date(1952, 11, 16), None,
     "Rua Antônio Pereira Freire, 05", "Triunfo", "(19) 99313-9345",
     "Ministra da Eucaristia (até 2019) / Liturgia", "Ativo", "Não",
     "Ministra da Eucaristia até 2019; hoje na Liturgia.", "p.6b"),
    (13, "13", "Devanira Vitta Lobão", "F", datetime.date(1947, 10, 15), None,
     "Rua das Crianças, 1162", "N. Sra. de Fátima", "(19) 99491-9890", "",
     "Ativo", "Não", "", "p.6b"),
    (14, "14", "Eneide Bernardes Grandini", "F", datetime.date(1936, 8, 28),
     datetime.date(1955, 1, 1), "Rua Frederico Lanzoni, 55", "Santa Luíza II",
     "(19) 3466-0924", "Pastoral dos Doentes / Ministra da Eucaristia", "Ativo", "Não",
     "Pertence ao Apostolado desde 1955 (Itapevi, Par. São Judas Tadeu); Nova Odessa desde 2000. "
     "Filha: Vera (19) 98188-2997. Pastoral dos Doentes – Ministra da Eucaristia.", "p.6b"),
    (15, "15", "Idione Michelan da Silva", "F", datetime.date(1965, 6, 29), None,
     "Rua Sebastião da Cruz Prata, 25", "Triunfo", "(19) 99320-4034", "",
     "Inativo", "Não", "Inativo na comunidade.", "p.7"),
    (16, "16", "Fátima Aparecida Felix Carmelossi", "F", datetime.date(1962, 1, 1), None,
     "Rua João Batista de Almeida, 16", "Triunfo", "(19) 99384-5859",
     "Ministra da Eucaristia", "Ativo", "Não",
     "Ministra da Eucaristia – Comunidade Sta. Luzia e Irmã Dulce.", "p.7"),
    (17, "17", "Helena Rosante (Helena de Fátima Rosante Caetano)", "F",
     datetime.date(1967, 5, 15), None, "Rua das Crianças, 1164", "N. Sra. de Fátima",
     "(19) 99280-8069", "", "Ativo", "Não",
     "Esposa de Osmar Caetano (#38). Verificar duplicidade com Helena (#45).", "p.7"),
    (18, "18", "Jair Rosante", "M", None, None,
     "Rua Jordano Milani, 148", "N. Sra. de Fátima", "(19) 99289-5207", "",
     "Ativo", "Não", "Irmão de Helena Rosante (#17). Aniversário não preenchido no livro.", "p.7"),
    (19, "19", "Jefferson Ap. Rosante Caetano", "M", datetime.date(2001, 8, 21), None,
     "Rua das Crianças, 1164", "N. Sra. de Fátima", "(19) 99888-9562", "",
     "Ativo", "Não", "Filho de Helena (#17) e Osmar Caetano (#38).", "p.7"),
    (20, "20", "Janete (Jeanete Batista da Silva)", "F", datetime.date(1964, 12, 21), None,
     "Rua Antônio Pereira Freire, 08", "Triunfo", "(19) 98138-3742",
     "Catequese (Coordenadora) / Terço", "Ativo", "Não",
     "Pastoral Catequese (Coordenadora); Terço.", "p.7"),
    (21, "21", "Karla", "F", datetime.date(2004, 9, 7), None,
     "Rua Maximiliano Dal Medico", "Santa Luíza II", "", "",
     "Ativo", "Não", "Sobrenome não registrado no livro.", "p.7b"),
    (22, "22", "Renata Cristina Rodrigues Scardovelli", "F", datetime.date(1975, 1, 23), None,
     "Rua Maximiliano Dal Medico, 774", "Santa Luíza II", "(19) 99274-6853", "",
     "Ativo", "Não", "", "p.7b"),
    (23, "23", "Lázaro Manoel da Silva Neto", "M", datetime.date(1961, 3, 30), None,
     "Rua Antônio Pereira Freire, 09", "Triunfo", "", "",
     "Ativo", "Não", "Telefone não preenchido.", "p.7b"),
    (24, "24", "Luiz Antônio", "M", datetime.date(1963, 9, 27), None,
     "Rua Joaquim Leite da Cunha, 1088", "Triunfo", "(19) 99478-8717",
     "Coordenador do Apostolado / Ministro da Eucaristia", "Ativo", "Não",
     "Coordenador do Apostolado da Oração.", "p.7b"),
    (25, "25", "Iara", "F", None, None,
     "Rua Joaquim Leite da Cunha, 1088", "Triunfo", "", "",
     "Ativo", "Não", "Aniversário: 23/12, ano ilegível. Possível esposa de Luiz Antônio (#24).", "p.7b"),
    (26, "26", "Teresa", "F", datetime.date(1933, 9, 19), None,
     "", "", "", "", "Falecida", "Não", "Faleceu – data do óbito não registrada no livro.", "p.7b"),
    (27, "27", "Luíza Regina", "F", datetime.date(1962, 3, 24), None,
     "", "", "", "Coordenadora do Apostolado", "Ativo", "Não",
     "Coordenadora do Apostolado (livro: Lúcia Regina, 24/03/1962).", "p.8"),
    (28, "28", "Luíza Marrick", "F", datetime.date(1942, 9, 25), None,
     "", "", "(19) 3466-1575", "", "Falecida", "Não", "Faleceu – data não registrada.", "p.8"),
    (29, "29", "Leonice", "F", datetime.date(1944, 12, 8), None,
     "", "", "", "", "Falecida", "Não", "Sobrenome não registrado. Faleceu.", "p.8"),
    (30, "30", "Maria José", "F", None, None,
     "", "", "", "", "Ativo", "Não", "Aniversário: 08/06, ano ilegível.", "p.8"),
    (31, "31", "Maria de Lourdes", "F", datetime.date(1943, 3, 16), None,
     "", "", "", "", "Falecida", "Não", "Faleceu – data não registrada.", "p.8"),
    (32, "32", "Rosa Pigato", "F", None, None,
     "", "", "", "", "Falecida", "Não", "Aniversário: 15/02, ano ilegível. Faleceu.", "p.8"),
    (33, "33", "Maria Soares", "F", None, None,
     "", "", "", "", "Falecida", "Não", "Aniversário completamente ilegível. Faleceu.", "p.8b"),
    (34, "34", "Nair Leal Domingos", "F", datetime.date(1939, 7, 11), datetime.date(1993, 1, 1),
     "Rua Irineu José Zordon, 75", "Santa Luíza II", "", "",
     "Ativo", "Não", "Participa do Apostolado desde 1993.", "p.8b"),
    (35, "35", "Neuza Rosa", "F", datetime.date(1956, 2, 26), None,
     "", "", "", "", "Ativo", "Não", "Endereço não informado no livro (NT).", "p.8b"),
    (36, "36", "Natalina", "F", datetime.date(1949, 12, 25), None,
     "Rua Aristides Benedito, 11", "Triunfo", "(19) 99296-3723", "",
     "Ativo", "Não", "", "p.8b"),
    (37, "37", "Olímpia Straiotto Garcia", "F", datetime.date(1939, 3, 20), None,
     "", "", "", "Coordenadora Apostolado – Comunidade Santa Luzia", "Falecida", "Não",
     "FALECEU EM 15/04/2024.", "p.8b"),
    (38, "38", "Osmar Caetano (marido da Helena)", "M", datetime.date(1962, 1, 2), None,
     "Rua das Crianças, 1164", "N. Sra. de Fátima", "", "",
     "Ativo", "Não", "Marido de Helena Rosante (#17).", "p.8b"),
    (39, "39", "Pedro", "M", datetime.date(2003, 2, 3), None,
     "", "", "", "", "Ativo", "Não", "Aniversário 03/02/2003 (livro p.9). Demais campos em branco.", "p.8b/9"),
    (40, "40", "Osinete Aparecida dos Santos", "F", datetime.date(1978, 8, 23), None,
     "Rua da Amizade, 282", "Terranova", "(19) 99525-5013", "",
     "Ativo", "Não", "Filha de Santa Luzia.", "p.9"),
    (41, "41", "Odete", "F", datetime.date(1948, 6, 21), None,
     "", "", "", "", "Ativo", "Não", "Sobrenome, endereço e telefone não registrados.", "p.9"),
    (42, "42", "Simone Aparecida Frizoni", "F", datetime.date(1988, 5, 21), None,
     "Rua João Batista de Almeida, 24", "Triunfo", "(19) 99287-6954", "",
     "Ativo", "Não", "Mesmo endereço de Eurípia Frizoni (#43).", "p.9"),
    (43, "43", "Eurípia Aparecida Rafael Frizoni", "F", datetime.date(1952, 8, 22), None,
     "Rua João Batista de Almeida, 24", "Triunfo", "(19) 99612-0246", "",
     "Ativo", "Não", "Mesma residência de Simone Frizoni (#42).", "p.9"),
    (44, "44", "Valdomira Marestoni (D. Nena)", "F", datetime.date(1945, 9, 14), None,
     "Rua Antônio Dorto Sobrinho, 89", "Santa Luíza I", "(19) 99373-1760", "",
     "Ativo", "Não", "Conhecida como D. Nena.", "p.9"),
    (45, "45", "Helena", "F", datetime.date(1943, 12, 4), None,
     "", "", "", "", "Ativo", "Não",
     "POSSÍVEL DUPLICIDADE com Helena Rosante (#17) – revisar urgente.", "p.9"),
    (46, "46", "Izabel Ferreira Lopes (Izabel)", "F", datetime.date(1963, 5, 1), None,
     "Rua João Batista de Almeida, 43", "Triunfo", "(19) 98176-9772", "",
     "Ativo", "Não", "", "p.9b"),
    (47, "47", "Iolanda", "F", datetime.date(1947, 12, 1), None,
     "", "", "", "", "Ativo", "Não", "Telefone e endereço não registrados.", "p.9b"),
    (48, "48", "Rosangela Alves Amorim de Oliveira", "F", datetime.date(1973, 6, 3),
     datetime.date(2019, 3, 1), "Rua Frederico Lanzoni, 191", "Santa Luíza II", "", "",
     "Ativo", "Não", "Membro desde 01/03/2019 – Paróquia São Jorge.", "p.9b"),
    (49, "49", "Marlene Degan Fabro", "F", datetime.date(1958, 10, 24),
     datetime.date(2025, 6, 6), "Alameda do Saber, 8", "Jd. Fibra", "(19) 99765-4390",
     "Pastoral Litúrgica", "Ativo", "Não",
     "Membro do Apostolado desde 06/06/2025. Pastoral Litúrgica – Irmã Dulce.", "p.9b"),
    (50, "50", "Luiz Ferreira de Paula", "M", None, None,
     "Rua Professor Antônio F. Gonçalves, 31", "Triunfo", "(11) 98740-5105",
     "Pastoral da Criança", "Ativo", "Não", "Pastoral da Criança – Santa Luzia. DDD 11.", "p.9b"),
    (51, "51", "Daiana Rocha Santos", "F", datetime.date(1951, 11, 12),
     datetime.date(2025, 6, 6), "Rua da Felicidade, 988", "Res. Fibra", "(19) 99404-8130", "",
     "Ativo", "Não", "Membro do Apostolado desde 06/06/2025.", "p.9b"),
    (52, "52", "Carlos José Amorim Nobuyasu", "M", datetime.date(2002, 8, 6),
     datetime.date(2026, 5, 20), "Rua Frederico Lanzoni, 181", "Residencial Santa Luíza II",
     "(19) 98845-5763", "", "Ativo", "Não",
     "Membro desde 20/05/2026. Provável parente de Rosangela Amorim (#48).", "p.10"),
    (53, "53", "Leila Barbosa Fonseca", "F", datetime.date(1966, 2, 6), None,
     "Rua da Amizade, 101", "Terra Nova", "(19) 99466-3688",
     "Ministra da Eucaristia", "Ativo", "Não",
     "Comunidade Santa Dulce dos Pobres. Participa de outra atividade pastoral: Ministra da Eucaristia. "
     "Ficha paróquia São Jorge.", "ficha"),
    (54, "54", "Maria Neusa Pessoa Pavan", "F", datetime.date(1966, 6, 15), None,
     "Rua da Alegria, 542", "Terra Nova", "(19) 99408-5302",
     "Leiga voluntária", "Desistente", "Sim",
     "Comunidade Santa Dulce dos Pobres. DESISTENTE. Leiga voluntária.", "ficha"),
    (55, "55", "Eliane Francisca dos Santos", "F", datetime.date(1955, 7, 15),
     datetime.date(2026, 5, 24), "Rua Joaquim Leite da Cunha, 901", "Santa Luíza I",
     "(11) 99304-0675",
     "Ministra da Eucaristia (Pastoral dos Doentes) / Coordenadora Comunidade Santa Luzia",
     "Ativo", "Sim", "Consagrada em 05/06/2026.", "p.10"),
    (56, "56", "Vera Lúcia de Abreu Rodão", "F", datetime.date(1977, 7, 4), None,
     "Rua Ângelo Piconi, 471", "Santa Luíza I", "(19) 99399-4599",
     "Pastoral do Batismo", "Ativo", "Sim",
     "Comunidade Santa Luiza. Pastoral do Batismo. Consagrada em 05/06/2026. "
     "Verificar duplicidade com Irene Pedrao (C2).", "ficha"),
    (102, "C2", "Irene Rosineia de Abreu Pedrao", "F", datetime.date(1977, 7, 4), None,
     "Rua Ângelo Diconi, 471", "Santa Luíza I", "(19) 99394-4579", "Pastoral do Batismo",
     "Ativo", "Não",
     "Ficha avulsa. Mesmo endereço e data nasc. de Vera Lucia (#56) – verificar.", "ficha"),
]

INCONSISTENCIAS = [
    ("Duplicidade potencial", "🔴 Crítica",
     "Helena (#45) sem sobrenome pode ser duplicata de Helena Rosante (#17).",
     "Revisar manualmente: confirmar se #45 é mesma pessoa de #17.", "Não"),
    ("Duplicidade potencial", "🟠 Alta",
     "Vera Lucia (#56) e Irene Pedrao (#102) – mesmo endereço (Rua Ângelo, 471) e mesma data de nascimento (04/07/1977).",
     "Verificar se são a mesma pessoa ou grafia diferente da rua (Piconi × Diconi).", "Não"),
    ("Situação confirmada", "🟠 Alta",
     "Maria Neusa Pessoa Pavan (#54) marcada como DESISTENTE.",
     "Retirar da rota de visitas. Guardar registro histórico.", "Não"),
    ("Aniversário incompleto", "🟠 Alta",
     "Iara (#25) – dia 23/12, ano ilegível.",
     "Solicitar confirmação do ano de nascimento.", "Não"),
    ("Aniversário incompleto", "🟠 Alta",
     "Maria José (#30) – dia/mês 08/06, ano ilegível.",
     "Solicitar confirmação do ano de nascimento.", "Não"),
    ("Aniversário incompleto", "🟠 Alta",
     "Rosa Pigato (#32) – dia/mês 15/02, ano ilegível. Falecida.",
     "Verificar com família.", "Não"),
    ("Aniversário incompleto", "🔴 Crítica",
     "Maria Soares (#33) – aniversário completamente ilegível. Falecida.",
     "Verificar com família.", "Não"),
    ("Falecimento sem data", "🟠 Alta",
     "Teresa (#26), Luíza Marrick (#28), Leonice (#29), Maria de Lourdes (#31), Rosa Pigato (#32), Maria Soares (#33) – datas de falecimento não registradas.",
     "Buscar datas nos registros da Paróquia.", "Não"),
    ("Falecimento confirmado com data", "🔵 Informativa",
     "Olímpia Straiotto Garcia (#37) – faleceu em 15/04/2024.",
     "Registro completo.", "Sim"),
    ("Sobrenome ausente", "🟡 Média",
     "17 membros sem sobrenome completo.",
     "Atualizar registros quando possível.", "Não"),
    ("Telefone parcialmente ilegível", "🟡 Média",
     "Cacilda(#6) – último dígito ilegível no livro.",
     "Solicitar atualização nas próximas visitas.", "Não"),
    ("Endereço vazio", "🟡 Média",
     "18 membros sem endereço registrado.",
     "Atualizar endereços nas próximas visitas.", "Não"),
    ("Lacuna na numeração", "🔵 Informativa",
     "Número 7 ausente entre Cacilda(#6) e Célia(#8).",
     "Conferir livro físico.", "Não"),
    ("Telefone DDD não local", "🔵 Informativa",
     "Luiz Ferreira(#50) DDD 11; Eliane(#55) DDD 11.",
     "Confirmar se são números atuais.", "Não"),
    ("Grafia no livro", "🔵 Informativa",
     "Lúcia/Luíza Regina (#27); Izabel/Iolanda conforme livro físico.",
     "Registro atualizado pelas fotos do livro.", "Sim"),
    ("Parentesco presumido", "🔵 Informativa",
     "Luiz Antônio(#24) & Iara(#25); família Rosante-Caetano; Frizoni; Cristina & Lucas (#9–10); Rosangela & Carlos.",
     "Registrar laço familiar nas observações.", "Não"),
    ("Consagração registrada", "🔵 Informativa",
     "Eliane (#55) e Vera Lucia (#56) consagradas em 05/06/2026.",
     "Data oficial registrada na coluna Observações.", "Sim"),
]

ITENS_ENTREGA = [
    "Camisa do Apostolado",
    "Imagem de Nossa Senhora",
    "Imagem do Sagrado Coração de Jesus",
    "Fita de Consagração",
    "Folheto de Oração Mensal",
    "Terço Bento",
    "Livro de Orações do Apostolado",
    "Convite para Reunião",
    "Boletim Paroquial",
    "Nenhum – visita de acompanhamento pastoral",
]

ORDEM_BAIRROS = [
    "Residencial Santa Luíza II",
    "Residencial Santa Luíza I",
    "Santa Luíza I",
    "Santa Luíza II",
    "N. Sra. de Fátima",
    "Triunfo",
    "Terranova",
    "Terra Nova",
    "Jd. Fibra",
    "Res. Fibra",
    "Nova Odessa",
    "",
]

MEMORIAL = [
    ("Teresa", datetime.date(1933, 9, 19), None, "#26 – Faleceu – data do óbito não registrada"),
    ("Luíza Marrick", datetime.date(1942, 8, 25), None, "#28"),
    ("Leonice", datetime.date(1944, 12, 8), None, "#29 – Sobrenome não registrado"),
    ("Maria de Lourdes", datetime.date(1943, 3, 16), None, "#31"),
    ("Rosa Pigato", None, None, "#32 – Aniversário ilegível"),
    ("Maria Soares", None, None, "#33 – Aniversário ilegível"),
    ("Olímpia Straiotto Garcia", datetime.date(1939, 3, 20), datetime.date(2024, 4, 15),
     "#37 – Coordenadora Apostolado Comunidade Santa Luzia"),
]

MEMBROS_SEED = MEMBROS
INCONSISTENCIAS_SEED = INCONSISTENCIAS

CONFIG_PADRAO = {
    "paroquia": "Paróquia São Jorge",
    "diocese": "Diocese de Limeira",
    "cidade": "Nova Odessa",
    "estado": "SP",
    "coordenador": "Luiz Antônio",
    "coordenadora": "Luíza Regina",
    "comunidades": "Santa Luzia · Santa Dulce dos Pobres · N. Sra. de Fátima · Paróquia São Jorge · Terra Nova · Triunfo",
    "arquivo_excel": "apostolado.xlsx",
    "backup_automatico": "Sim",
    "dias_backup": "30",
    "tema_cor": "#6A1B9A",
    "whatsapp_coordenador": "",
    "observacoes_sistema": "Sistema Apostolado da Oração – Nova Odessa",
}
