[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#FFFFFF"
backgroundColor = "#4A148C"
secondaryBackgroundColor = "#6A1B9A"
textColor = "#FFFFFF"
font = "sans serif"

[client]
toolbarMode = "minimal"
showSidebarNavigation = true
