[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#B388FF"
backgroundColor = "#3E1078"
secondaryBackgroundColor = "#5E35B1"
textColor = "#FFFFFF"
font = "sans serif"

[client]
toolbarMode = "minimal"
showSidebarNavigation = true

[runner]
fastReruns = true
