[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#4A148C"
backgroundColor = "#311B92"
secondaryBackgroundColor = "#4A148C"
textColor = "#FFFFFF"
font = "sans serif"

[client]
toolbarMode = "minimal"
showSidebarNavigation = true

[runner]
fastReruns = true
